apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: e3yp3yer8-go
  janus-idp.io/tekton: e3yp3yer8-go
  backstage.io/kubernetes-id: e3yp3yer8-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: e3yp3yer8-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
