apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: e3yp3yer8-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:cc5720bf444a2f3e9216e9c38c19da57fbbcea45@sha256:fe6d5db1ac3b086f0293b1cfbd8bb6811e092af8bf6512b2a0736a0226426cda
          name: container-image
